name: too_good_notify_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - boto3
    - pydantic
    - python-telegram-bot
    - python_dateutil
    - pytz
    - python-dotenv
    - requests
    - tgtg