name: TooGoodNotify
channels:
  - defaults
dependencies:
  - python=3.10
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-asyncio
  - pip
  - pip:
    - boto3
    - pydantic
    - python-telegram-bot
    - python_dateutil
    - pytz
    - python-dotenv
    - requests
    - pytest-freezegun
    - freezegun